# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-raycast" do
  version "0.6.5"

  on_macos do
    sha256 "b963c09ec144fda8bbc256a958b03e3705ef14e861e1c602084e1b374a4b99e0"
    url "https://github.com/jag-k/git-raycast/releases/download/v#{version}/git-raycast.tar.gz",
        verified: "github.com/jag-k/git-raycast"
  end

  name "git-raycast"
  desc "Automate git using Raycast AI"
  homepage "https://github.com/jag-k/git-raycast"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-raycast"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-raycast"]
    end
  end

  generate_completions_from_executable "git-raycast",
    base_name: "git-raycast",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  generate_completions_from_executable "git-raycast", "git-completion",
    base_name: "git_raycast",
    shells: [:bash, :zsh]

  # No zap stanza required

end
