# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-raycast" do
  version "0.6.0"

  on_macos do
    sha256 "2902d8758652b70baf911833a5e2a04926c7d5777eeacdbeba30bb2fbbfa8826"
    url "https://github.com/jag-k/git-raycast/releases/download/v#{version}/git-raycast.tar.gz",
        verified: "github.com/jag-k/git-raycast"
  end

  name "git-raycast"
  desc "Automate git using Raycast AI"
  homepage "https://github.com/jag-k/git-raycast"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-raycast"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-raycast"]
    end
  end
  generate_completions_from_executable "bin/git-raycast", "completion",
    base_name: "git-raycast",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
