# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-raycast" do
  name "git-raycast"
  desc "Automate git using Raycast AI"
  homepage "https://github.com/jag-k/git-raycast"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-raycast"
  bash_completion "git-raycast.bash"
  zsh_completion "git-raycast.zsh"
  fish_completion "git-raycast.fish"

  on_macos do
    url "https://github.com/jag-k/git-raycast/releases/download/v#{version}/git-raycast.tar.gz",
        verified: "github.com/jag-k/git-raycast"
    sha256 "61f25a33be1b8af1cfb3ce0fbb026c200c80d1ff6d3023e05d00813f8112d95c"
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-raycast"]
    end
  end

  # No zap stanza required
end
